### ISSUE TITLE
Request: Implicit time.Duration parsing

### ISSUE THREAD

**Issue by Tri125** [BurntSushi/toml#145]
At the moment only a field named "duration" in the toml configuration file will be parsed into a time.Duration type. If you write your own Go type you can always map it to a more appropriately named field.

However, this is less than ideal when you are mapping the toml configuration to a type defined from an imported package.

For instance, for the configuration of my database connection I have my toml file matching the fields of the Config type as defined by the [github.com/go-sql-driver/mysql package](https://godoc.org/github.com/go-sql-driver/mysql#Config) : 

```
[database]
user = "root"
passwd = "toor"
net = "tcp"
#addr = "127.0.0.1:3306"
dbname = "db_1"
timeout = "90s"
strict = true
parseTime = true
```

The matching structure is the following:

```
type MyConf struct {
	DB      mysql.Config `toml:"database"`
        [...]
}
```

Unfortunately, timeout will be treated simply as a string by the toml parser and renaming "timeout" to "duration" will, obviously, not parse it to the timeout field of the mysql.Config type and the database connection will not have a defined timeout.

**Comment by cespare** [comment]
> At the moment only a field named "duration" in the toml configuration file will be parsed into a time.Duration type. If you write your own Go type you can always map it to a more appropriately named field.

This isn't correct -- this library doesn't care what you name your field.

When decoding, any value implementing encoding.TextUnmarshaler will be automatically loaded by calling that method. time.Duration does not implement that interface, but it is easy to write your own type which does -- see the `type duration` example [in the README](https://github.com/BurntSushi/toml#using-the-encodingtextunmarshaler-interface).

Or maybe what you're asking for is to specially handle time.Durations as though they were TextMarshaler/TextUnmarshalers? If so, I'm hesitant for 3 reasons:

1. This breaks backwards compatibility because right now you *can* marshal/unmarshal time.Durations as nanosecond numbers
2. I'd like to not introduce more special cases into encoding/decoding
3. encoding/json doesn't do this

**Comment by Tri125** [comment]
My deepest apologies, I rushed to conclusion from my testing and I didn't read the doc properly.

Thank you for your quick reply.
