### ISSUE TITLE
Can't encode a map with interface{} keys, even if the keys are strings

### ISSUE THREAD

**Issue by hairyhenderson** [BurntSushi/toml#178]
Sometimes I hit situations where I have a map like:

```go
m := map[interface{}]interface{}{"foo": "bar"}
```

IMO, this _should_ encode cleanly to TOML:

```toml
foo = "bar"
```

But when I try this, I get an error: `toml: cannot encode a map with non-string key type`.

I encounter maps like this most often when I decode YAML with libraries like [`gopkg.in/yaml.v2`](https://github.com/go-yaml/yaml/tree/v2), and unfortunately since YAML supports more than just `string` as a key type, they have to use `interface{}` as the key type.

I think this is fixable by simply attempting to coerce the key (here: https://github.com/BurntSushi/toml/blob/master/encode.go#L276). i.e. `mapKey.Interface().(string)` instead of `mapKey.String()`.

I'll submit a PR to do this if my approach makes sense.

**Comment by cespare** [comment]
I think it's reasonable that the maps you pass in have to have string key types for the same reason that encoding/json only supports maps with string/int keys.

``` go
package main

import (
	"encoding/json"
	"log"
	"os"
)

func main() {
	m := map[interface{}]interface{}{"foo": "bar"}
	if err := json.NewEncoder(os.Stdout).Encode(m); err != nil {
		log.Fatal(err)
	}
}

// gives
// json: unsupported type: map[interface {}]interface {}
```

If you need to support arbitrary data like this, convert the maps to string-keyed maps first.

**Comment by arp242** [comment]
I can see how it solves a practical issue, but on the other hand, it complicates things and the more features like this you add, the more edge cases you get. You'll have to support it forever too as removing a feature like this would be a breaking change.

Like cespare mentioned, you should be able to convert it to a `map[string]interface{}` without too many problems? Unless this really solves an issue that's hard to solve otherwise I think it's best to not add this for now, as it's not clear to me that this really solves something that would be hard otherwise.

I'll close this issue for the time being, but feel free to get back to it and we can reopen.

**Comment by hairyhenderson** [comment]
Fair enough. Given that TOML keys may only be strings, I get the reasoning.

**Comment by arp242** [comment]
Cheers; like I said, always willing to reconsider if there's a good use case that's hard to solve otherwise. Practicality beats purity.

**Comment by arp242** [comment]
#181 might be a good/better solution for this by the way; you can add `type mykey interface{}` and add the `TextMarshaler` and `TextUnmarshaler`, which should work for both TOML and YAML.

I'll probably add that (unless some unexpected complexities turn up, I don't expect there will be but I'm not sure as I haven't been maintaining this for very long), although probably not in the next release.

If you're still interested in this, it would make a good PR. And I promise it will be reviewed faster this time 😅 Otherwise I'll get round to it at point.
