### ISSUE TITLE
More helpful usage guidance on errors

### ISSUE THREAD

**Issue by axxelG** [BurntSushi/toml#201]
It would be nicer to give a more helpfull and easyer to understand error message if unescaped backslashes are causing a panic.

Cureent error message for `C:\Users\`
`expected eight hexadecimal digits after '\U', but got "C:\\Us`

**Comment by arp242** [comment]
Ah, I closed your PR in #202 as I didn't quite understand the point of it, but with the context of using `path = "C:\Users\"` your PR makes a lot more sense 😅 Sorry, I just took over maintainership and going through all the issues and missed this.

Still not entirely sure what to do with this, because anything I can think of results in a very long error and I'm not a huge fan of that either. I'm somewhat thinking that we need to extend the way error reporting in general is being done and split things out in a "concise message" and "usage guidance", but I'm not entirely sure what/how yet 🤔 This would be useful for quite a few error messages, not just this one.

I'll retitle the issue to reflect this.
