### ISSUE TITLE
Support UTF-8 with BOM

### ISSUE THREAD

**Issue by aegoroff** [BurntSushi/toml#233]
Now the lib doesn't support toml files in UTF-8 encoding with BOM

**Comment by aaaasmile** [comment]
Yes, I got this error:

> Near line 0 (last key parsed ''): bare keys cannot contain '\ufeff'

It happens to me when i tried to modify an UTF8 toml file with Notepad on windows server. Notepad was saving as default the file with BOM and the result ist that the parser was't working anymore.

**Comment by arp242** [comment]
UTF-8 shouldn't have a BOM; it looks like you're trying to read a UTF-16 file and the TOML specification supports only UTF-8. Since #276 the error on that should be clearer.

**Comment by BurntSushi** [comment]
@arp242 Unfortunately, it's somewhat common for UTF-8 encoded files on Windows to have a BOM. Byte order is of course an irrelevant concept for UTF-8. As far as I can tell, it's mostly only useful as a signal that the file _is_ UTF-8 encoded, even though its use is nowhere near universal.

(The way I've handled the UTF-8 BOM in other projects is mostly to just look for it, allow it, but otherwise ignore it.)

**Comment by arp242** [comment]
Oh right, what a curious thing to do.

I'll change it to ignore it then; the other UTF-16 check should still work to produce reasonable errors.

**Comment by arp242** [comment]
Fixed it now in #277
