### ISSUE TITLE
v0.4 no longer allows leading zeros

### ISSUE THREAD

**Issue by davidnewhall** [BurntSushi/toml#318]
I'm very happy this project got some updates! That said, the new version broke a few of my apps. I can live with it, but I just wanted to explain my use case. I don't expect any fixes; I just wanted to share my experience with the new version.

My apps write log files. I allow my users to put a file mode. ie. `file_mode = 0644`. This uses a format that most users are familiar with: `chmod` input.

The new version, following TOML spec, now returns an error. For references, here's a snippet of my code.
```golang
// LogConfig allows sending logs to rotating files.
type LogConfig struct {
	LogFile   string   `toml:"log_file"`
	FileMode  FileMode `toml:"file_mode"`
}

// FileMode is used to unmarshal a unix file mode from the config file.
type FileMode os.FileMode

// UnmarshalText turns a unix file mode, wrapped in quotes or not, into a usable os.FileMode.
func (f *FileMode) UnmarshalText(text []byte) error {
	str := strings.TrimSpace(strings.Trim(string(text), `"'`))

	fm, err := strconv.ParseUint(str, 8, 32)
	if err != nil {
		return fmt.Errorf("file_mode (%s) is invalid: %w", str, err)
	}

	*f = FileMode(os.FileMode(fm))

	return nil
}
```

My only question is: Can the UnmarshalText interface run before trying to turn unquoted strings into numbers? For now, I'll just set my example config files to use `"0644"` (quoted). Thank you for your time!

**Comment by arp242** [comment]
I presume the error you're running in to is:

> Near line 3 (last key parsed 'file_mode'): Invalid integer "0644": cannot have leading zeroes

Previously it would allow leading zeros, but this was never valid TOML and always explicitly disallowed (even in older versions of the spec), so was a bug in this library. This kind of situation sucks because breaking compatibility is bad, but remaining "bug compatible" also is :-(

First it lexes the TOML file; at this point it doesn't have any knowledge of any Go type information of your struct, and then it uses the struct's type information to scan the values. UnmarshalValue() is only intended to scan (valid!) TOML syntax in a different type, but scanning invalid TOML syntax isn't really something you can do.

As for your question, there isn't really a good way to express this in TOML; this isn't really a limitation of this specific library, but rather just not something you can express in the TOML syntax. You will either need to use a string (`"0644"`, `'0644'`) or octals as `0o644` or  `0o0644`. Allowing it to parse `file_mode = 0644` would basically mean allowing it to parse invalid TOML.

Maybe a `AllowLeadingZeros` flag could be added, I'm not principally opposed to it or anything, but also not entirely sold on it (yet) since you're the first person to report this issue in the 2 months the new version has been out, so I'm not sure if this is a problem a lot of people will have or just you. But that's pretty much the only option I can think of right now.

I will update the title to reflect the specific change and leave this issue open for now so other people can chime in with their experiences. In the meanwhile I'll have a think about it.

**Comment by davidnewhall** [comment]
Yo yo! Appreciate the thorough and prompt response! I don't personally feel this is a bad problem to have. You answered my question and I'm perfectly comfortable with that answer. I'm just glad I was able to figure out why we were getting this error, and yes, it's exactly the error you wrote. I'll keep my fingers crossed that whomever maintains the TOML spec also has a reason to put file modes in a config file. Please don't go coding in new override/special thingies on my account. We can add quotes to our files, I wrote my unmarshaler to take them long ago. Thanks again!

**Comment by arp242** [comment]
> I'll keep my fingers crossed that whomever maintains the TOML spec also has a reason to put file modes in a config file.

The TOML specification is maintained at https://github.com/toml-lang/toml and anyone is free to join in to make suggestions to improve it.

Personally I think that using merely a leading zero to denote an octal number would be confusing (as experience with many languages with such a feature has demonstrated), but would be in favour of merely ignoring leading zeros (i.e. `0644` is base-10 644, but your custom unmarshal is of course free to interpret that as base-8, as it currently does) unless someone comes with a good argument to not support it.

I can't find any previous discussion on this in the toml spec repo. You can try opening an issue explaining your use case and see what others think.

**Comment by arp242** [comment]
It's been quite a while, and no one else reported experiencing any problems with this, so I think it's probably safe to close this now as no further actions are needed (such as adding a setting for it), as there doesn't seem to be any demand for it.

**Comment by davidnewhall** [comment]
Thank you.
