### ISSUE TITLE
Lowercase type definition not accepted.

### ISSUE THREAD

**Issue by jtagcat** [BurntSushi/toml#323]
Unsure if this a bug or if it's me not knowing how to computer enough.

From [`_examples/example.go`](https://github.com/BurntSushi/toml/blob/e0af6a256822c45317ce8c57358ec8ef186e6abc/_examples/example.go):
```go
package main

import (
	"fmt"

	"github.com/BurntSushi/toml"
)

type tomlConfig struct {
	Title string
}

func main() {
	var config tomlConfig
	if _, err := toml.DecodeFile("example.toml", &config); err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("Title: %s\n", config.Title)
}
```

^^^ works; now however, if we change `s/Title/title/g`:
```go
package main

import (
	"fmt"

	"github.com/BurntSushi/toml"
)

type tomlConfig struct {
	title string
}

func main() {
	var config tomlConfig
	if _, err := toml.DecodeFile("what.toml", &config); err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("Title: %s\n", config.title)
}
```

The variable is left empty.

For both, example.toml has one line in it:
```toml
title = "TOML Example"
```

**Comment by arp242** [comment]
Yeah, this is because the field isn't exported – it works like that with all encoding packages (e.g encoding/json) too.

The problem is we're accessing your struct from another package (this toml package), so it needs to be exported.

It's annoying and easy mistake to make, but not much that can be done about it.

**Comment by jtagcat** [comment]
Thanks for the explanation, I understand and agree.
