### ISSUE TITLE
Unexpected behaviour with the TextMarshaler interface

### ISSUE THREAD

**Issue by alessandro-guido** [BurntSushi/toml#357]
The toml packages behaves unexpectedly when using the TextMarshaler interface. In particular, the toml package ignores a MarshalText implementation if the receiver is a pointer but the value to be serialized is not, like in the following example.

```
type Document struct {
	Field IntSlice
}

type IntSlice []int

func (items *IntSlice) MarshalText() ([]byte, error) {
    ...
}
```

I've tried to setup a complete example here: https://go.dev/play/p/tMLzMg5sqTe. The json package, IMHO correctly, makes use of the MarshalText defined as above. Changing the signature like below is required to make the toml package use the custom MarshalText function.
```
func (items IntSlice) MarshalText() ([]byte, error) {
```

Decoding interface is not affected by this problem, i.e. an UnmarshalText function is picked even if it has a pointer type receiver (tested locally, not shown in the example code).

**Comment by arp242** [comment]
Does this still happen in the latest master? Some changes were made last week (specifically: #354).

**Comment by alessandro-guido** [comment]
Yes, it does. Tested with BurntSushi/toml@v1.1.1-0.20220529223624-8fccf3c6afbe

**Comment by arp242** [comment]
Alrighty, just checking!

There is actually already a test case for this: https://github.com/BurntSushi/toml/blob/master/encode_test.go#L342-L343 – although it tests that it "fails" rather than works.

I took a quick look, and encoding/json contains some additional code to handle this, in `newTypeEncoder()`. Need to look a bit at how that works and adjust `Encoder.encoder` accordingly here.

To set expectations: I probably won't have time for this in the next few weeks, but I'll review patches if you feel like taking a crack at it.

**Comment by kkHAIKE** [comment]
@arp242 make a fix for it, https://github.com/BurntSushi/toml/pull/358
😊
