### ISSUE TITLE
Nonstandard license name

### ISSUE THREAD

**Issue by nlacey** [BurntSushi/toml#373]
Thanks for the great work. And I've found your license in your COPYING  file
but this is a non standard license name
Normally a license would be called LICENSE or LICENSE.md

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

I'm using software to collate licenses, and it didn't find yours automatically

Thanks

**Comment by BurntSushi** [comment]
`COPYING` is absolutely standard. Just because whatever tool you're using doesn't recognize it doesn't mean it's not standard. Examples:

* https://github.com/curl/curl/blob/master/COPYING
* https://github.com/git/git/blob/master/COPYING
* https://github.com/torvalds/linux/blob/master/COPYING
* https://github.com/rpm-software-management/rpm/blob/master/COPYING
* https://github.com/file/file/blob/master/COPYING
* https://github.com/zeek/zeek/blob/master/COPYING
* https://github.com/westes/flex/blob/master/COPYING

**Comment by arp242** [comment]
COPYING is the name what many GNU projects use; "Add a COPYING file with a copy of the GNU GPL or GNU AGPL." is in the [GPL usage instructions](https://www.gnu.org/licenses/gpl-howto.html).

I don't know if it originated from the GNU/GPL people, but it's very commonly used by GPL and many (if not all?) GNU projects. If "whatever GNU is doing" isn't "standard" then I don't know what is.

"LICENSE" does seem more popular today, but if the tool doesn't recognize "COPYING" then you're going to run in to trouble with a lot of different projects. There are a number of other filenames in common-ish use too, see e.g. https://github.com/golang/pkgsite/blob/8996ff632abee854aef1b764ca0501f262f8f523/internal/licenses/licenses.go#L83

I believe GitHub also has an API, for projects hosted by GitHub, and the pkg.go.dev site also has license information, although I'm not sure if they have a good API for that.

**Comment by nlacey** [comment]
Hi guys, thanks so much for the information!  I appreciate it!
