### ISSUE TITLE
-2000000000 is not a valid float32 data

### ISSUE THREAD

**Issue by nhuythuy** [BurntSushi/toml#396]
Hi,

If I use -2000000000 as a float32 value, I received error "-2000000000 is out of range for float32" (tested with TOML v1.3.2,  docker on Windows 10, 64 bit)

I check the data type then toml found that it is int64, not float32 as specified

Data structure:

    type Sensor struct {
	Name        string  `toml:"name"`
	Address     uint16  `toml:"address"`
	Unit        string  `toml:"unit"`
	DataType    string  `toml:"data_type"`
	Bit         int     `toml:"bit"`
	ScaleFactor float32 `toml:"scale_factor"`
	ScaleOffset float32 `toml:"scale_offset"`
	WordOrder   string  `toml:"word_order"`
	ByteOrder   string  `toml:"byte_order"`
	Description string  `toml:"description"`
    }

.toml file:

    sensors = [
        {address = 100,  unit = "V",   data_type = "uint16", bit = -1, scale_factor = 1, scale_offset = -2000000000, byte_order = "big", word_order = "little", name = "value", description = "---"},    
    ]

**Comment by arp242** [comment]
It gives an error as `-2000000000` is out of the range of "safe" float32 natural numbers (which is `-16777215` through `16777215`). Numbers outside that range can not always be represented accurately in a float32.

For example you can see this with:

	func main() {
		var m struct{ X float32 }
		_, err := toml.Decode(`x = -2000000001.0`, &m)
		fmt.Printf("%v: %f %f\n", err, m.X, float32(-2000000001))
	}

Which outputs the wrong numbers, because there is no way to represent that accurately in a float32:

    <nil>: -2000000000.000000 -2000000000.000000

---

It only checks for this if you used an int value without a fraction (`-2000000000` instead of `-2000000000.0`, which is why the above example works). I think that's probably okay behaviour, but it should be documented. The error is also unclear and should be improved.

As for your problem, you can either add that `.0` and accept the loss of accuracy, or use a `float64` or an int type (float64 ranges are to ~9×10¹⁶ instead of ~1.6×10⁷, so that should be enough for your purpose.)

**Comment by nhuythuy** [comment]
Thanks for clear explanation.

You are right, I have fixed it by specified -2000000000.0 and planed to use float64, but forgot to mention. It is better to have clearer message

Thuy
