### ISSUE TITLE
Encoding of non-struct and map used to fail now succeeds

### ISSUE THREAD

**Issue by wader** [BurntSushi/toml#397]
Hello

I'm update from 1.2.1 to 1.3.2 for https://github.com/wader/fq and i have some round-trip tests that used to fail but now seems to succeed and i'm a bit confused if it's bug or intended.

For example encoding of 123 used to fail with `top-level values must be Go maps or structs` but now encodes to `"123"` if i then try to decode this it fails.

Example round-trip for 123: https://go.dev/play/p/0mzfhNnb_Kt

**Comment by wader** [comment]
Thanks for quick reply! could it be confusing that encode can produce non-valid TOML "document"? in the case of JSON i think it's (more?) common that primitives values are encoded/decoded on their own?

Either way works for me. For fq i think i will probably somehow not allow it for decoding as TOML "overlaps" with JSON.

**Comment by arp242** [comment]
> could it be confusing that encode can produce non-valid TOML "document"?

It does produce valid TOML data though; e.g. in the form of a string, array, datetime, etc. This can be useful for custom marshals and the like; I've done that with JSON, and although less common in TOML I generally prefer for things to behave identical to the json package unless there's a good reason not to, because that's what people are used to and leads to the fewest surprises.

**Comment by wader** [comment]
Yeap true. Anyways i think we can close this issue, thanks for clarifying and thanks for working on this TOML package!
