### ISSUE TITLE
Cannot decode interface

### ISSUE THREAD

**Issue by didip** [BurntSushi/toml#62]
Not being able to decode interface, is that a known behavior? See below, Storage is an interface:
Type mismatch for 'backend.ProxyBackend.Storage': Unsupported type 'interface'.

**Comment by oblitum** [comment]
Not sure whether it's related but it seems so. In my case I wish I could decode a TOML that was already decoded to an `interface{}` (which ends up creating a tree of map[string]T) to a given `struct`.

**Comment by oblitum** [comment]
meaning that besides the route string/file -> interface{}/definite-type I wish I could also string/file -> interface{} -> definite-type.

**Comment by oblitum** [comment]
This would allow one to pick subtrees to put in small definite struct data types.

**Comment by cespare** [comment]
Closing this because

1. The original report is missing the required information.
2. The subsequent feature request by @oblitum doesn't seem like a good idea, for the same reason that encoding/json doesn't support this kind of API. (If the request were for a toml equivalent of json.RawMessage, that could make sense, but that wasn't mentioned here.)

**Comment by cespare** [comment]
Re: (2) I forgot that `toml.Primitive` exists. That is the mechanism you probably want, @oblitum.
