### ISSUE TITLE
Environment variable support?

### ISSUE THREAD

**Issue by stephenmuss** [BurntSushi/toml#80]
Environment variable support could be quite useful.

See [Mozilla's Heka](https://hekad.readthedocs.org/en/latest/config/index.html#using-environment-variables) for an example of how it could work.

Is this something you would consider?

**Comment by BurntSushi** [comment]
Unlikely. Thus far, I've kept pretty strict compliance with the spec and I'd like to continue that. That means it will probably be up to the application to implement on top of TOML. Perhaps there is a reusable component that could be extracted from Heka and put into a separate library?

**Comment by stephenmuss** [comment]
I did have a quick look at their source but maybe I'll go back and take another. Thanks for your input.

**Comment by dodwyer** [comment]
This seems to be the commit in question: https://github.com/ecnahc515/heka/commit/6ed5cb4ab6718edaff00775fadf6c213af0b89d3
I'm reviewing this so we can enable env variables in confd TOML files as discussed here: https://github.com/kelseyhightower/confd/issues/131

**Comment by supershal** [comment]
+1 for Environment variable support in toml parser.
We need to inject values from environment variable easily specially when we are trying to run an application as docker container in a isolated environment.
Yes, we can write custom code on top of toml to inject env variable values in the file or override them code itself. 
However it become difficult when you want to dockerize third party applications without modifying it's source code or deployment mechanism. We can't use them as it is in container environments. 
I would love to have this implemented in the parser itself as a convention so that it can be used by all applications. 

@BurntSushi if you strongly believe this requirement should be in toml spec, then we should ask community to add it to the spec.

**Comment by cespare** [comment]
I don't see why a toml library (or the spec) ought to know about environment variables. That seems like a concern for the systems which use toml.

**Comment by o3o3o** [comment]
👍  for Environment variable support in toml parser.
We use confd in docker container, the env is defined in Dockerfile, so I think it will be useful for the env variable support in toml.
